### ISSUE TITLE
How to stream MIME into mail-parser?

### ISSUE THREAD

**Issue by arifd** [stalwartlabs/mail-parser#76]
Hello, and thank you for this fantastic crate!

I have a concern though,`MessageParser` can only accept an in-memory collection of bytes, rather than for example `Read`,  since MIME is itself a multipart format, and emails could (thereotically) have infinite amounts or sized attachments etc, is there something obvious that I am missing?

**Comment by arifd** [comment]
Ah right. that is a good point!

I am desiging a system that should be able to parse emails from various sources, I want to follow the [Robustness principle](https://en.wikipedia.org/wiki/Robustness_principle) which in short, says:

> be conservative in what you send, be liberal in what you accept

For that reason, I was thinking about "what if someone gives me an infinite sized EML".  Is this something that can be fairly trivial to build on top of mail-parser, or do you think if I wanted to solve this problem, I should look elsewhere?

**Comment by mdecimus** [comment]
But how would someone generate an infinite sized EML? The number of parts in an EML will always be limited by the file size which is finite. As long as the EML fits in memory, `mail-parser` can parse any number of parts included in it. 

However, as I mentioned before, it is wise to limit the maximum size of messages and parts you accept in order to avoid attacks. Practically all mail server providers impose limits on message sizes and MIME parts.
